version: '{build}'
image:
  - Visual Studio 2017
skip_tags: true
clone_depth: 10
environment:
  matrix:
    - JAVA_HOME: C:\Program Files\Java\jdk1.8.0
    - JAVA_HOME: C:\Program Files\Java\jdk11

build_script:
  - mvn -B -V clean verify
cache:
  - C:\Users\appveyor\.m2
