<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>test.resolution-scope</groupId>
    <artifactId>parent</artifactId>
    <version>1.0-SNAPSHOT</version>
  </parent>
  <artifactId>app</artifactId>
  <properties>
    <api.scope>provided</api.scope>
    <lib.scope>compile</lib.scope>
    <lib.artifactId>lib</lib.artifactId>
    <lib.optional>false</lib.optional>
    <searchTransitive>true</searchTransitive>
  </properties>
  <dependencies>
    <dependency>
      <groupId>test.resolution-scope</groupId>
      <artifactId>${lib.artifactId}</artifactId>
      <version>1.0-SNAPSHOT</version>
      <type>pom</type>
      <scope>${lib.scope}</scope>
      <optional>${lib.optional}</optional>
    </dependency>
    <dependency>
      <groupId>test.resolution-scope</groupId>
      <artifactId>container</artifactId>
      <version>1.0-SNAPSHOT</version>
    </dependency>
    <dependency>
      <groupId>test.resolution-scope</groupId>
      <artifactId>api</artifactId>
      <version>1.0-SNAPSHOT</version>
      <scope>${api.scope}</scope>
    </dependency>
  </dependencies>
  <build>
    <plugins>
      <plugin>
        <artifactId>maven-enforcer-plugin</artifactId>
        <version>@enforcerPluginVersion@</version>
        <dependencies>
          <dependency>
            <groupId>@project.groupId@</groupId>
            <artifactId>@project.artifactId@</artifactId>
            <version>@project.version@</version>
          </dependency>
        </dependencies>
        <configuration>
          <rules>
            <banDuplicateClasses>
              <findAllDuplicates>true</findAllDuplicates>
              <searchTransitive>${searchTransitive}</searchTransitive>
            </banDuplicateClasses>
          </rules>
        </configuration>
      </plugin>
    </plugins>
  </build>
  <profiles>
    <profile>
      <id>compile</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-enforcer-plugin</artifactId>
            <configuration>
              <rules>
                <banDuplicateClasses>
                  <resolutionScope>compile</resolutionScope>
                </banDuplicateClasses>
              </rules>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>runtime</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-enforcer-plugin</artifactId>
            <configuration>
              <rules>
                <banDuplicateClasses>
                  <resolutionScope>runtime</resolutionScope>
                </banDuplicateClasses>
              </rules>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>test</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-enforcer-plugin</artifactId>
            <configuration>
              <rules>
                <banDuplicateClasses>
                  <resolutionScope>test</resolutionScope>
                </banDuplicateClasses>
              </rules>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>invalid</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-enforcer-plugin</artifactId>
            <configuration>
              <rules>
                <banDuplicateClasses>
                  <resolutionScope>complie</resolutionScope>
                </banDuplicateClasses>
              </rules>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>scan-compile</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-enforcer-plugin</artifactId>
            <configuration>
              <rules>
                <banDuplicateClasses>
                  <scopes>
                    <scope>compile</scope>
                  </scopes>
                </banDuplicateClasses>
              </rules>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>ignore-provided</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-enforcer-plugin</artifactId>
            <configuration>
              <rules>
                <banDuplicateClasses>
                  <ignoredScopes>
                    <ignoredScope>provided</ignoredScope>
                  </ignoredScopes>
                </banDuplicateClasses>
              </rules>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>ignore-optionals</id>
      <build>
        <plugins>
          <plugin>
            <artifactId>maven-enforcer-plugin</artifactId>
            <configuration>
              <rules>
                <banDuplicateClasses>
                  <ignoreOptionals>true</ignoreOptionals>
                </banDuplicateClasses>
              </rules>
            </configuration>
          </plugin>
        </plugins>
      </build>
    </profile>
    <profile>
      <id>transitive-runtime</id>
      <dependencies>
        <dependency>
          <groupId>test.resolution-scope</groupId>
          <artifactId>runtime-lib</artifactId>
          <version>1.0-SNAPSHOT</version>
          <type>pom</type>
        </dependency>
      </dependencies>
    </profile>
  </profiles>
</project>
